- project:
    templates:
      - golang-jobs
    check:
      jobs:
        - golang-lint
        - libnetwork-build-image
        - libnetwork-integration-centos7
    gate:
      jobs:
        - golang-lint
        - libnetwork-build-image
        - libnetwork-integration-centos7
    periodic:
      jobs:
        - libnetwork-build-image
        - libnetwork-integration-centos7-rpm
- job:
    name: libnetwork-build-image
    parent: nuage-build-docker-image
    nodeset: centos-7
    required-projects:
      - nuagenetworks/nuage-libnetwork
    vars:
      vsp_release: "{{ nuage_vsp_release }}"
      zuul_work_dir: "{{ ansible_user_dir }}/src/github.com"
      container_command: docker
      docker_images:
        - context: nuagenetworks/nuage-libnetwork
          go_task: build
          dockerfile: Dockerfile
          repository: nuage/libnetwork

- job:
    name: libnetwork-integration-centos7
    parent: deployment-docker-centos-7
    dependencies: libnetwork-build-image
    post-run: ci/post.yaml
    vars:
      libnetwork_deployment: container
      test_regex: 'nuage_container_tests.tests.docker'

- job:
    name: libnetwork-integration-centos7-rpm
    parent: libnetwork-integration-centos7
    vars:
      libnetwork_deployment: rpm
