FROM registry.mv.nuagenetworks.net:5000/build/golang:1.9

RUN yum install -y rpm-build &&\
    mkdir -p /BUILD/go/src/github.com/nuagenetworks/nuage-libnetwork

WORKDIR /BUILD/go/src/github.com/nuagenetworks/nuage-libnetwork
